---
- hosts: install
  tasks:
  - include_vars: ./global.yml
  - name: update compose.yml removing non-required ISO uploads
    copy: src=files/compose.yml dest=/root/digitalrebar/deploy/tasks/compose.yml
  - name: remove network config
    file: dest=digitalrebar/deploy/compose/config-dir/api/config/networks/the_admin.jsoni.mac state=absent
  - name: update network config
    template: src=templates/the_admin_json.j2 dest=digitalrebar/deploy/compose/config-dir/api/config/networks/the_admin.json.mac
  - name: update compose environment for proxy
    lineinfile: dest=/root/digitalrebar/deploy/compose/common.env line="UPSTREAM_PROXY_ADDRESS=67.20.167.99"
  - name: update compose environmet proxy port
    lineinfile: dest=/root/digitalrebar/deploy/compose/common.env line="UPSTREAM_PROXY_PORT=3128"
#  - name: get core code to allow network update
#    git: clone=yes repo=https://github.com/digitalrebar/core/ dest=/root/digitalrebar/core/
#  - name: update network barclamp
#    file: src=files/network.yml dest=/root/digitalrebar/core/barclamps/network.yml
  - name: run rebar install script
    command: ./run-in-system.sh --deploy-admin=local --admin-ip={{installserver.mgmt_ip}}/{{installserver.mgmt_netmask|ipaddr('prefix')}} --access=HOST --con-provisioner --con-dhcp --wl-hardware --wl-docker chdir=/root/digitalrebar/deploy
    register: rebar_out
  - debug: var=rebar_out
