---
- hosts: oshypervisors:compute
  become: true
  become_user: root
  tasks:
  - name: import variables
    include_vars: ./global.yml
  - name: import physical information
    include_vars: ./physical.yml
  - name: import network information
    include_vars: ./network.yml
  - name: update hostname
    template: dest=/etc/hostname src=templates/hostname.j2
  - name: force hostname
    command: hostnamectl set-hostname {{inventory_hostname}}.{{internal_domain}}
  - name: add physical hosts to /etc/hosts in advance of DNS updates
    lineinfile: "dest=/etc/hosts insertafter=EOF line='{{item.value.mgmt_ip}} {{item.value.name}}.{{internal_domain}} {{item.value.name}}'"
    with_dict: "{{physical}}"
    when: not item.value.name == 'none'

  - name: ensure bridge-utils are installed
    yum: name=bridge-utils state=latest
  - name: configure enp129s0f0
    template: src=templates/ifcfg_enp129s0f0.j2 dest=/etc/sysconfig/network-scripts/ifcfg-enp129s0f0
  - name: configure enp129s0f1
    template: src=templates/ifcfg_enp129s0f1.j2 dest=/etc/sysconfig/network-scripts/ifcfg-enp129s0f1
  - name: create a br0 bridge
    command: brctl addbr br0
  - name: add bridge interface config in network scripts
    copy: src=files/ifcfg-br0 dest=/etc/sysconfig/network-scripts/ifcfg-br0
  - name: update bond0 to associate it with br0
    template: src=templates/ifcfg_bond.j2 dest=/etc/sysconfig/network-scripts/ifcfg-bond0
  - name: add bond0+mgmtVlan with public IP/gateway
    template: src=templates/ifcfg_br0_m.j2 dest=/etc/sysconfig/network-scripts/ifcfg-br0.{{network.infrastructuremanagement.vlan}}

